<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sony-VAIO" name="TC005_Delete_Employee_Record" tests="7" failures="2" timestamp="12 Nov 2019 17:34:55 GMT" time="1.108" errors="0">
  <testcase name="checkResponseBody" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseBody" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.restAssuredTestCases.TC005_Delete_Employee_Record.checkResponseBody(TC005_Delete_Employee_Record.java:37)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkStatusCode" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkResponseTime" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.restAssuredTestCases.TC005_Delete_Employee_Record.checkResponseTime(TC005_Delete_Employee_Record.java:60)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkStatusLine" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record"/>
  <testcase name="checkContentType" time="0.0" classname="com.restAssuredTestCases.TC005_Delete_Employee_Record"/>
</testsuite> <!-- TC005_Delete_Employee_Record -->
