<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sony-VAIO" name="TC003_Post_Employee_Record" tests="6" failures="1" timestamp="12 Nov 2019 17:34:52 GMT" time="1.452" errors="0">
  <testcase name="checkResponseBody" time="0.0" classname="com.restAssuredTestCases.TC003_Post_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.11" classname="com.restAssuredTestCases.TC003_Post_Employee_Record"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.restAssuredTestCases.TC003_Post_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkResponseTime" time="0.032" classname="com.restAssuredTestCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.restAssuredTestCases.TC003_Post_Employee_Record.checkResponseTime(TC003_Post_Employee_Record.java:71)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkStatusLine" time="0.015" classname="com.restAssuredTestCases.TC003_Post_Employee_Record"/>
  <testcase name="checkContentType" time="0.0" classname="com.restAssuredTestCases.TC003_Post_Employee_Record"/>
</testsuite> <!-- TC003_Post_Employee_Record -->
